trigger:
  - main

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              npm install
            displayName: "npm install"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: "MyNeighbours_BlockChain_Environment_Staging"
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: "Azure subscription 1(2)(06a6013b-95aa-4307-aa1e-e958d7327334)"
                    appType: "webApp"
                    WebAppName: "my-neighbours-blockchain-staging-app-service"
                    packageForLinux: "$(Pipeline.Workspace)/**/*.zip"
                    ScriptType: "Inline Script"
                    InlineScript: "node index.js"
                    enableCustomDeployment: true
                    DeploymentType: "zipDeploy"
